package report

const htmlTemplate = `{{define "header"}}<!doctype html>
<html lang="en" data-mode="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="dark light">
<title>llm-slo-bench run report</title>
<style>
{{.UPlotCSS}}
:root{--mono:'Geist Mono',ui-monospace,SFMono-Regular,Menlo,monospace;--bg:#faf5ec;--surface:#f4ecdf;--ink:#000;--muted:#4d4947;--ink-body:#1a1a1a;--accent:#e07000;--on-accent:#000;--added:#007038;--open:#00667a;--data:#7340bf;--removed:#c2334a;--border:#202020;--rule:#202020;--hairline:#00000022;--body-weight:400}
html[data-mode="dark"]{--bg:#0a0a0a;--surface:#141414;--ink:#eeeae4;--muted:#a8a29b;--ink-body:#cfc9c0;--accent:#ff8100;--on-accent:#000;--added:#00c26e;--open:#00abd6;--data:#af85ff;--removed:#ff6b81;--border:#4d4947;--rule:#6b6560;--hairline:#ffffff24;--body-weight:450}
*{box-sizing:border-box;border-radius:0}html{-webkit-font-smoothing:antialiased}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--mono);font-size:14px;line-height:1.6;font-weight:var(--body-weight)}::selection{background:var(--accent);color:var(--on-accent)}:focus-visible{outline:1px solid var(--accent);outline-offset:3px}
.topbar{position:sticky;top:0;z-index:40;background:var(--surface);border-bottom:1px solid var(--border)}.topbar-in{width:100%;min-height:54px;padding:10px 24px;display:flex;align-items:center;justify-content:space-between;gap:16px}.topbar-title{min-width:0;color:var(--muted);font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.topbar-title b{color:var(--ink)}.topbar-actions{display:flex;align-items:center;margin-left:auto}.tgl{background:none;border:0;padding:4px;margin:0;color:var(--ink);cursor:pointer;display:flex;align-items:center}.tgl:hover{color:var(--accent)}.i-sun{display:block}.i-moon{display:none}html[data-mode="dark"] .i-sun{display:none}html[data-mode="dark"] .i-moon{display:block}
main{width:100%;padding:42px 24px 96px}.hero{display:grid;grid-template-columns:minmax(260px,.75fr) minmax(0,2.25fr);gap:clamp(28px,5vw,88px);padding-bottom:42px;border-bottom:1px solid var(--rule)}.sec-label{font-size:14px;letter-spacing:.5px;text-transform:uppercase;font-weight:700;color:var(--ink);margin-bottom:16px}.sec-label b{color:var(--accent)}.section-rule{border-top:1px solid var(--rule);padding-top:11px;display:flex;align-items:center;gap:10px;font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);font-weight:600;margin-bottom:22px}.section-rule i{width:8px;height:8px;background:var(--accent);flex:none;margin-left:auto}h1{font-size:clamp(34px,5vw,68px);line-height:1.03;letter-spacing:-.03em;font-weight:700;margin:0 0 18px}h2{font-size:clamp(22px,2.5vw,34px);line-height:1.14;letter-spacing:-.02em;margin:0}.lede{color:var(--muted);max-width:84ch;margin:0}.sec{margin-top:68px}.muted,.caption{color:var(--muted)}.caption{font-size:12px;margin:10px 0 0}code{font:inherit;color:var(--ink);background:var(--surface);border:1px solid var(--hairline);padding:1px 4px;overflow-wrap:anywhere}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));border:1px solid var(--border)}.cell{padding:14px 15px;min-width:0;border-right:1px solid var(--hairline);border-bottom:1px solid var(--hairline)}.label{display:block;color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:5px}.value{font-size:18px;overflow-wrap:anywhere}.pending,.partial,.unavailable{color:var(--open)}.complete{color:var(--added)}.note{border:1px solid var(--border);border-left:4px solid var(--open);background:var(--surface);padding:14px 16px;color:var(--muted);margin:14px 0}.note strong{color:var(--open)}
.outcome-layout{display:grid;grid-template-columns:minmax(280px,.8fr) minmax(0,2.2fr);gap:24px}.outcome-bar{display:flex;width:100%;height:38px;border:1px solid var(--border);background:var(--surface)}.outcome-bar span{display:block;height:100%;border-right:1px solid var(--bg);min-width:0}.outcome-bar span:last-child{border-right:0}.outcome-bar .success{background:var(--added)}.outcome-bar .dropped{background:var(--data)}.outcome-bar .canceled{background:var(--accent)}.outcome-bar .failed{background:var(--removed)}.legend{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));border:1px solid var(--border);border-top:0}.legend-item{padding:10px 12px;border-right:1px solid var(--hairline);display:grid;grid-template-columns:8px 1fr auto;gap:8px;align-items:center;font-size:12px}.legend-item i{width:8px;height:8px;background:var(--muted)}.legend-item.success i{background:var(--added)}.legend-item.dropped i{background:var(--data)}.legend-item.canceled i{background:var(--accent)}.legend-item.failed i{background:var(--removed)}.legend-item b{font-weight:700}.legend-item span{color:var(--muted)}
.charts{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));border:1px solid var(--border)}.chart{padding:16px;border-right:1px solid var(--hairline);border-bottom:1px solid var(--hairline);min-width:0}.chart-head{display:flex;justify-content:space-between;gap:12px;margin-bottom:14px}.chart-head b{font-size:15px}.chart-head span{font-size:11px;color:var(--muted)}.bar-row{display:grid;grid-template-columns:34px minmax(0,1fr) 86px;gap:10px;align-items:center;margin:8px 0;font-size:11px}.track{height:11px;border:1px solid var(--hairline);background:var(--surface)}.fill{display:block;height:100%;background:var(--accent)}.bounds{display:flex;justify-content:space-between;color:var(--muted);font-size:10px;border-top:1px solid var(--hairline);padding-top:8px;margin-top:12px}
.table-wrap{width:100%;border:1px solid var(--border);overflow-x:auto}.tbl{border-collapse:collapse;width:100%;font-size:12px}.tbl th{text-align:right;font-weight:700;padding:10px 12px;border-bottom:1px solid var(--border);font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:var(--muted);background:var(--surface);white-space:nowrap}.tbl td{text-align:right;padding:9px 12px;border-bottom:1px solid var(--hairline);vertical-align:top;white-space:nowrap}.tbl th:first-child,.tbl td:first-child{text-align:left}.tbl tr:last-child td{border-bottom:0}.empty{text-align:left!important;color:var(--muted)}
.plot{border:1px solid var(--border);background:var(--surface);padding:12px;min-width:0}.plot-host{width:100%;height:230px;min-width:0}.plot-host .uplot{font-family:var(--mono)!important}.plot-host .u-legend{color:var(--ink);font-family:var(--mono);font-size:11px}.plot-host .u-wrap{max-width:100%}.plot-host canvas,.plot-host .u-cursor-pt{border-radius:0}.distribution-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(420px,1fr));border:1px solid var(--border)}.distribution{padding:14px;border-right:1px solid var(--hairline);border-bottom:1px solid var(--hairline);min-width:0}.distribution h3{font-size:14px;margin:0 0 10px}.strip-labels{display:flex;justify-content:space-between;color:var(--muted);font-size:10px;margin-top:8px}
details{border:1px solid var(--border);background:var(--surface)}summary{cursor:pointer;padding:14px 16px;color:var(--ink);font-weight:700}.details-body{padding:0 16px 16px}.license{width:100%;margin-top:12px}.license pre{white-space:pre-wrap;overflow-wrap:anywhere;color:var(--muted);font:11px/1.55 var(--mono);margin:0;padding:0 14px 14px}footer{border-top:1px solid var(--border);margin-top:68px;padding-top:16px;color:var(--muted);font-size:12px;display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap}
@media(max-width:900px){.hero,.outcome-layout{grid-template-columns:1fr}.charts,.distribution-grid{grid-template-columns:1fr}}
@media(max-width:700px){.topbar-in{padding-left:14px;padding-right:14px}main{padding:28px 14px 64px}.hero{padding-bottom:30px}.sec{margin-top:52px}.charts,.distribution-grid{display:block}.chart,.distribution{border-right:0}.bar-row{grid-template-columns:30px minmax(0,1fr) 78px}.plot-host{height:210px}.tbl,.tbl thead,.tbl tbody,.tbl tr,.tbl th,.tbl td{display:block}.tbl thead{display:none}.tbl tr{border-bottom:1px solid var(--border);padding:8px 0}.tbl tr:last-child{border-bottom:0}.tbl td{border:0;white-space:normal;text-align:left;padding:4px 10px;overflow-wrap:anywhere}.tbl td::before{content:attr(data-label);display:block;color:var(--muted);font-size:9px;letter-spacing:.08em;text-transform:uppercase}.tbl td:first-child{padding-top:7px;font-weight:700}.tbl td:last-child{padding-bottom:7px}.tbl .empty::before{content:none}.details-body{padding:0 10px 10px}.legend{grid-template-columns:1fr 1fr}}
@media(max-width:390px){.legend{grid-template-columns:1fr}.topbar-title{font-size:11px}.value{font-size:16px}}
</style>
</head>
<body>
<div class="topbar"><div class="topbar-in"><div class="topbar-title"><b>LLM-SLO-BENCH</b> &nbsp;·&nbsp; run report · schema v{{.Summary.SchemaVersion}}</div><div class="topbar-actions"><button class="tgl" id="mode" aria-label="Toggle colour mode"><svg class="i-sun" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41"/></svg><svg class="i-moon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/></svg></button></div></div></div>
<main>
<header class="hero"><div><div class="sec-label">[ <b>RUN REPORT</b> ]</div><div class="section-rule">Inference benchmark <i></i></div></div><div><h1>Measured performance,<br>without inference.</h1><p class="lede">A portable rendering of one immutable metrics summary. Percentile bars show exactly the exported p50, p90, p95 and p99 values against each metric's exported min/max bounds.</p></div></header>

<section class="sec"><div class="sec-label">[ <b>RUN CONTEXT</b> ]</div><div class="section-rule">Identity and provenance <i></i></div><div class="grid">
<div class="cell"><span class="label">Run ID</span><span class="value">{{.Metadata.RunID}}</span></div><div class="cell"><span class="label">Scenario</span><span class="value">{{.Metadata.Scenario}}</span></div><div class="cell"><span class="label">Target</span><span class="value">{{.Metadata.Target}}</span></div><div class="cell"><span class="label">Model</span><span class="value">{{.Metadata.Model}}</span></div><div class="cell"><span class="label">Started</span><span class="value">{{.Metadata.StartedAt}}</span></div><div class="cell"><span class="label">Duration</span><span class="value">{{.Metadata.Duration}}</span></div><div class="cell"><span class="label">Config fingerprint</span><span class="value"><code>{{.Metadata.ConfigFingerprint}}</code></span></div></div></section>

<section class="sec"><div class="sec-label">[ <b>SLO GATES</b> ]</div><div class="section-rule">Evaluation state <i></i></div><div class="note"><strong class="pending">PENDING</strong> SLO evaluation is not attached to this metrics summary. This report does not infer or fabricate pass/fail results.</div></section>

<section class="sec"><div class="sec-label">[ <b>OUTCOMES</b> ]</div><div class="section-rule">Request taxonomy and rates <i></i></div><div class="outcome-layout"><div class="grid"><div class="cell"><span class="label">Scheduled</span><span class="value">{{.Summary.Counts.Scheduled}}</span></div><div class="cell"><span class="label">Started</span><span class="value">{{.Summary.Counts.Started}}</span></div><div class="cell"><span class="label">Error rate</span><span class="value">{{if .ZeroScheduled}}n/a{{else}}{{percent .Summary.Counts.ErrorRate}}{{end}}</span></div><div class="cell"><span class="label">Drop rate</span><span class="value">{{if .ZeroScheduled}}n/a{{else}}{{percent .Summary.Counts.DroppedRate}}{{end}}</span></div></div><div data-chart="outcomes"><div class="outcome-bar" aria-label="Outcome taxonomy as percentages of scheduled requests">{{range .Outcomes}}<span class="{{.Class}}" style="width:{{.Width}}%" title="{{.Name}}: {{.Count}} ({{.Percentage}})"></span>{{end}}</div><div class="legend">{{range .Outcomes}}<div class="legend-item {{.Class}}"><i></i><b>{{.Name}}</b><span>{{.Count}} · {{.Percentage}}</span></div>{{end}}</div><p class="caption">Each segment is the exact outcome count divided by scheduled requests. No distribution is estimated.</p></div></div>{{if .ZeroScheduled}}<div class="note">Rates are not applicable because no arrivals were scheduled.</div>{{end}}</section>

<section class="sec"><div class="sec-label">[ <b>PERCENTILES</b> ]</div><div class="section-rule">Exported statistics, bounded by observed min and max <i></i></div><div class="charts" data-chart="percentiles">{{range .Metrics}}<div class="chart"><div class="chart-head"><b>{{.Name}}</b>{{if .Summary}}<span>{{.Summary.Count}} samples · {{.Summary.Unit}}</span>{{else}}<span>no samples</span>{{end}}</div>{{if .Summary}}{{range .Bars}}<div class="bar-row"><b>{{.Label}}</b><div class="track"><span class="fill" style="width:{{.Width}}%"></span></div><span>{{.Value}}</span></div>{{end}}<div class="bounds"><span>min {{number .Summary.Min}}</span><span>max {{number .Summary.Max}}</span></div>{{else}}<div class="muted">No exported histogram statistics are available.</div>{{end}}</div>{{end}}</div><p class="caption">Bars encode only the four exported percentile values. They do not imply a continuous distribution or interpolate between percentiles.</p></section>

<section class="sec"><div class="sec-label">[ <b>LATENCY DISTRIBUTIONS</b> ]</div><div class="section-rule">Real bounded HDR percentile curves <i></i></div><div class="distribution-grid">{{range .Metrics}}{{if .DistributionJSON}}<div class="distribution"><h3>{{.Name}}</h3><div class="plot"><div class="plot-host distribution-plot" id="distribution-{{.ID}}" data-unit="{{.Summary.Unit}}"></div></div><script type="application/json" id="distribution-{{.ID}}-data">{{.DistributionJSON}}</script></div>{{end}}{{end}}</div><p class="caption">Each curve is exported from the underlying HDR histogram and capped at 100 points. No values are reconstructed from p50/p90/p95/p99.</p></section>

<section class="sec"><div class="sec-label">[ <b>HISTOGRAM CONTRACT</b> ]</div><div class="section-rule">Complete exported summary <i></i></div><div class="table-wrap"><table class="tbl"><thead><tr><th>Metric</th><th>Count</th><th>Min</th><th>Mean</th><th>P50</th><th>P90</th><th>P95</th><th>P99</th><th>Max</th><th>Lowest trackable</th><th>Highest trackable</th><th>Significant figures</th><th>Unit</th></tr></thead><tbody>{{range .Metrics}}<tr><td data-label="Metric">{{.Name}}</td>{{if .Summary}}<td data-label="Count">{{.Summary.Count}}</td><td data-label="Min">{{number .Summary.Min}}</td><td data-label="Mean">{{number .Summary.Mean}}</td><td data-label="P50">{{number .Summary.P50}}</td><td data-label="P90">{{number .Summary.P90}}</td><td data-label="P95">{{number .Summary.P95}}</td><td data-label="P99">{{number .Summary.P99}}</td><td data-label="Max">{{number .Summary.Max}}</td><td data-label="Lowest trackable">{{number .Summary.LowestTrackable}}</td><td data-label="Highest trackable">{{number .Summary.HighestTrackable}}</td><td data-label="Significant figures">{{.Summary.SignificantFigures}}</td><td data-label="Unit">{{.Summary.Unit}}</td>{{else}}<td class="empty" colspan="12">no samples</td>{{end}}</tr>{{end}}</tbody></table></div></section>

<section class="sec"><div class="sec-label">[ <b>USAGE + COST</b> ]</div><div class="section-rule">Authoritative provider totals only <i></i></div><div class="grid"><div class="cell"><span class="label">Usage status</span><span class="value {{.UsageState}}">{{.UsageState}}</span></div><div class="cell"><span class="label">Usage samples</span><span class="value">{{.Summary.Usage.Samples}}</span></div><div class="cell"><span class="label">Prompt tokens</span><span class="value">{{.PromptTokens}}</span></div><div class="cell"><span class="label">Completion tokens</span><span class="value">{{.OutputTokens}}</span></div><div class="cell"><span class="label">Total tokens</span><span class="value">{{.TotalTokens}}</span></div><div class="cell"><span class="label">Cost</span><span class="value">{{.Cost}}</span></div></div><div class="note">{{.UsageNote}}</div></section>

{{if .HasRequests}}<section class="sec"><div class="sec-label">[ <b>REQUEST TIMELINE</b> ]</div><div class="section-rule">TTFT by request order <i></i></div>{{if .TTFTStrip.HasData}}<div class="plot" data-chart="ttft-strip"><div class="plot-host" id="ttft-strip" data-x-min="{{.TTFTStrip.XMin}}" data-x-max="{{.TTFTStrip.XMax}}" data-y-min="{{.TTFTStrip.YMin}}" data-y-max="{{.TTFTStrip.YMax}}"></div><script type="application/json" id="ttft-strip-data">{{.TTFTStrip.DataJSON}}</script><div class="strip-labels"><span>min {{.TTFTStrip.Min}}</span><span>request order</span><span>max {{.TTFTStrip.Max}}</span></div></div><p class="caption">TTFT by validated request order from {{.TTFTStrip.Observed}} observed values. Rendering is bounded to 120 points by online downsampling; hard cap: 120 points.</p>{{else}}<div class="note">The JSONL detail contains no TTFT observations, so no timeline is shown.</div>{{end}}</section>
<section class="sec"><div class="sec-label">[ <b>REQUEST RECORDS</b> ]</div><div class="section-rule">{{.RequestCount}} validated records · {{.RequestSource}} <i></i></div><details><summary>Show per-request details</summary><div class="details-body"><div class="table-wrap"><table class="tbl requests"><thead><tr><th>#</th><th>Outcome</th><th>HTTP</th><th>TTFB</th><th>TTFT</th><th>Chunk ITL</th><th>Duration</th><th>Usage</th><th>Prompt tokens</th><th>Completion tokens</th><th>Total tokens</th></tr></thead><tbody>{{end}}
{{end}}
{{define "request"}}<tr><td data-label="#">{{.Number}}</td><td data-label="Outcome">{{.Record.Outcome}}</td><td data-label="HTTP">{{.Record.StatusCode}}</td><td data-label="TTFB">{{.TTFB}}</td><td data-label="TTFT">{{.TTFT}}</td><td data-label="Chunk ITL">{{.ChunkITL}}</td><td data-label="Duration">{{.Duration}}</td><td data-label="Usage">{{.Record.UsageStatus}}</td><td data-label="Prompt tokens">{{.PromptTokens}}</td><td data-label="Completion tokens">{{.CompletionTokens}}</td><td data-label="Total tokens">{{.TotalTokens}}</td></tr>{{end}}
{{define "footer"}}{{if .HasRequests}}</tbody></table></div></div></details></section>{{end}}<footer><span>Generated by llm-slo-bench.</span><span>Self-contained · zero external assets · schema v{{.Summary.SchemaVersion}}</span><details class="license"><summary>uPlot license · MIT</summary><pre>{{.UPlotLicense}}</pre></details></footer></main><script>{{.UPlotJS}}</script><script>(function(){"use strict";var root=document.documentElement,plots=[];function token(name){return getComputedStyle(root).getPropertyValue(name).trim()}function bound(host,name){var value=host.dataset[name];return value==null?null:Number(value)}function chartOptions(host,xLabel,yLabel){var xMin=bound(host,'xMin'),xMax=bound(host,'xMax'),yMin=bound(host,'yMin'),yMax=bound(host,'yMax');return{width:Math.max(260,host.clientWidth),height:host.clientHeight,legend:{show:true},cursor:{drag:{x:false,y:false}},scales:{x:{time:false,min:xMin,max:xMax},y:{min:yMin,max:yMax}},series:[{label:xLabel},{label:yLabel,stroke:token('--accent'),width:1.5,points:{show:false}}],axes:[{stroke:token('--muted'),grid:{stroke:token('--hairline')},ticks:{stroke:token('--border')},font:'11px '+token('--mono')},{stroke:token('--muted'),grid:{stroke:token('--hairline')},ticks:{stroke:token('--border')},font:'11px '+token('--mono')} ]}}function addPlot(host,data,xLabel,yLabel){if(!host||!data||!data[0]||data[0].length===0)return;plots.push(new uPlot(chartOptions(host,xLabel,yLabel),data,host))}document.querySelectorAll('.distribution-plot').forEach(function(host){var data=JSON.parse(document.getElementById(host.id+'-data').textContent);addPlot(host,data,'percentile',host.dataset.unit)});var strip=document.getElementById('ttft-strip');if(strip)addPlot(strip,JSON.parse(document.getElementById('ttft-strip-data').textContent),'request','TTFT ms');function rebuild(){var specs=plots.map(function(plot){return{host:plot.root.parentElement,data:plot.data,x:plot.series[0].label,y:plot.series[1].label}});plots.forEach(function(plot){plot.destroy()});plots=[];specs.forEach(function(spec){addPlot(spec.host,spec.data,spec.x,spec.y)})}var resizeTimer;window.addEventListener('resize',function(){clearTimeout(resizeTimer);resizeTimer=setTimeout(rebuild,120)});document.getElementById('mode').addEventListener('click',function(){root.dataset.mode=root.dataset.mode==='dark'?'light':'dark';rebuild()})})();</script></body></html>{{end}}`
